version: '3'

services:
  website:
    build: ./website
    volumes:
      - ./api:/usr/src/app
    ports:
      - 5002:80



  api-service:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 5003:80

    depends_on:
      - website

